// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' ;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh6niWBv6GQSgml1I0p5kxC6GxwJKDC3s',
    appId: '1:556270026815:web:f68df5b0ea8178d3ed788a',
    messagingSenderId: '556270026815',
    projectId: 'cityguideapp-67252',
    authDomain: 'cityguideapp-67252.firebaseapp.com',
    databaseURL: 'https://cityguideapp-67252-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cityguideapp-67252.appspot.com',
    measurementId: 'G-KQR4S0DC6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMFs6INYGXaLI_lYEbqDLGW5n-TeIbhYk',
    appId: '1:556270026815:android:9a05c0ea0069a639ed788a',
    messagingSenderId: '556270026815',
    projectId: 'cityguideapp-67252',
    databaseURL: 'https://cityguideapp-67252-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cityguideapp-67252.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYu2uCYjMcl-ZspTytcyN2mQhXEYRnFSM',
    appId: '1:556270026815:ios:65b50b1e99bdb783ed788a',
    messagingSenderId: '556270026815',
    projectId: 'cityguideapp-67252',
    databaseURL: 'https://cityguideapp-67252-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cityguideapp-67252.appspot.com',
    iosBundleId: 'com.example.cityGuideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYu2uCYjMcl-ZspTytcyN2mQhXEYRnFSM',
    appId: '1:556270026815:ios:aabfec2446f786eaed788a',
    messagingSenderId: '556270026815',
    projectId: 'cityguideapp-67252',
    databaseURL: 'https://cityguideapp-67252-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cityguideapp-67252.appspot.com',
    iosBundleId: 'com.example.cityGuideApp.RunnerTests',
  );
}
